#!/usr/bin/env bash
# Script that prints infinitely and handles SIGTERM gracefully
# Define what to do on SIGTERM
trap 'echo "I am invincible!!!"' SIGTERM
# Infinite loop
while true
do
   echo "To infinity and beyond"
    sleep 2
done
